In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 2, 3])

In [ ]:
y = np.array([4, 5, 6])

In [ ]:
print(x + y)

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 4], [2, 5, 6]])
print(a)
print(b)

In [ ]:
print(a * b)

In [ ]:
np.arange(100)

In [ ]:
t = np.arange(-np.pi, np.pi, 0.05)
print(t)
print(t.size)

In [ ]:
x = np.sin(t)
print(x)

In [ ]:
import matplotlib.pyplot as plt
plt.plot(t, x)

In [ ]:
t2 =np.linspace(1, 2, 100)
print(t2)

In [ ]:
np.linspace(1,10,4)

In [ ]:
n5 = np.arange(1, 50, 2).reshape(5, 5)
print(n5)

In [ ]:
n6 = np.linspace(1,100,30).reshape(15, 2)
print(n6)

In [ ]:
# 30 = 30 elements [1d]
# 6 x 5 = 30 elements [2d]
# 3 x 10 = 30 elements  
# 2 x 15 = 30 elements
# 5 x 6 = 30 elements
# 10 x 3 = 30 elements
# 15 x 2 = 30 elements
# 30 x 1 = 30 elements
# 3 x 5 x 2 = 30 elements [3d]
# 5 x 3 x 2 = 30 elements [3d]


In [ ]:
np.random.randint(10000, 99999, 10)

In [ ]:
ne = np.random.randint(0,9, (3, 3))
print(ne)

In [53]:
# permutation
np.random.permutation(100).reshape(10, 10)

array([[40, 76, 26,  3, 19, 14, 27,  1, 35, 63],
       [58, 43, 83, 74, 60, 36,  0, 64, 99, 52],
       [ 6, 65, 97, 28, 33, 72, 18, 16, 78, 95],
       [70,  2, 84, 96, 85, 39, 77, 66, 31, 21],
       [55, 24, 17, 41, 12, 90, 53, 91, 50, 88],
       [ 9, 92, 51, 11, 73, 87, 67, 30, 22,  8],
       [69, 20, 86, 98, 46, 32, 49, 59, 38, 10],
       [23, 54, 44, 37,  4, 25, 42, 48, 34, 89],
       [47, 68, 57, 15, 75,  5, 29, 45, 13, 79],
       [56, 94, 80, 81, 61, 62, 71, 82,  7, 93]])

In [ ]:
np.eye(10, dtype=int)

In [58]:
# numpy maths
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y) # add
print(x - y) # subtract
print(x * y) # multiply elementwise
print(x / y) # divide
print(x ** y) # power
print(x % y) # modulus
print(x // y) # floor division

# dot product
print(np.dot(x, y))
# cross product
print(np.cross(x, y))
# inner product
print(np.inner(x, y))
# outer product
print(np.outer(x, y))
# matrix multiplication
print(np.matmul(x, y))

# numpy statistics
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(x.sum()) # sum
print(x.mean()) # mean
print(x.std()) # standard deviation
print(x.var()) # variance
print(x.min()) # minimum
print(x.max()) # maximum
print(x.argmin()) # index of minimum
print(x.argmax()) # index of maximum
print(x.cumsum()) # cumulative sum
print(x.cumprod()) # cumulative product

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[1 2 3]
[0 0 0]
32
[-3  6 -3]
32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
32
36
4.5
2.29128784747792
5.25
1
8
0
7
[ 1  3  6 10 15 21 28 36]
[    1     2     6    24   120   720  5040 40320]


In [67]:
# trigonometry  
x = np.array([0, 30, 45, 60, 90])
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.deg2rad(x))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [68]:
# 10 x 10 matrix
x = np.arange(100).reshape(10, 10)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### slicing syntax for 1d array 
```
array[start:stop:step]
```
### slicing syntax for 2d array 
```
array[start:stop:step, start:stop:step]
```

In [71]:
print(x[0]) # first row
print(x[3, 5]) # element at row 3, column 5
print(x[:, 0]) # first column
print(x[:3, -1]) # first 3 rows, last column
print(x[:3, :3]) # first 3 rows, first 3 columns
print(x[:, [2, 4, 6]]) # columns 2, 4, 6

[0 1 2 3 4 5 6 7 8 9]
35
[ 0 10 20 30 40 50 60 70 80 90]
[ 9 19 29]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
[[ 2  4  6]
 [12 14 16]
 [22 24 26]
 [32 34 36]
 [42 44 46]
 [52 54 56]
 [62 64 66]
 [72 74 76]
 [82 84 86]
 [92 94 96]]


In [73]:
np.nan # not a number (missing value)

nan

In [74]:
np.inf # infinity

inf